### ISSUE TITLE
Ensure navigation correctly reflects current page state

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/mandelbrot#37] opened 2016-08-17 09:37 UTC
When I link to (documentation) pages directly, the relevant item in the sidebar navigation is highlighted. However, should it have a parent folder(s), these are not opened to reveal it, meaning the navigation doesn’t truly reflect the current view state.

Does that make any sense?! Basically, if an item in the nav is highlighted, ensure it’s parent folder(s) are opened too.

**Comment by allmarkedup** [comment] 2016-08-17 11:40
Yes, makes perfect sense. I thought it already did that actually so I'm classing this as a bug :-)

**Comment by mihkeleidast** [comment] 2020-04-03 17:54
Closing, since in my testing this works correctly. We can re-open if this is still relevant in some scenario, but that would need a better reproducible test case.

**Closed as completed by mihkeleidast** 2020-04-03 17:54 UTC
Labels: bug, [area] behavior
